import java.util.ArrayList;
import java.util.List;

// This class represents a payroll system that manages employees and their paychecks.
public class PayrollSystem {

    // A list of all the employees in the system.
    public List<Employee> employees;

    // A list of all the paychecks generated by the system.
    public List<Paycheck> paychecks;

    // Constructor that initializes the employee and paycheck lists.
    public PayrollSystem() {
        employees = new ArrayList<>();
        paychecks = new ArrayList<>();
    }

    // Add a new employee to the system.
    public void addEmployee(Employee employee) {
        employees.add(employee);
    }

    // Add a new paycheck to the system.
    public void addPayCheck(Paycheck paycheck){
        paychecks.add(paycheck);
    }

    // Remove an employee from the system.
    public void removeEmployee(Employee employee) {
        employees.remove(employee);
    }
}
